package pelicantun

import (
	"testing"

	cv "github.com/glycerine/goconvey/convey"
)

func TestGenPelicanKey(t *testing.T) {

	cv.Convey("Pelican keys generated by GenPelicanKey() should verify with IsLegitPelicanKey(), and random bytes should not", t, func() {

		k := GenPelicanKey()
		k2 := GenPelicanKey()

		r1 := RandBytes(149)
		r2 := RandBytes(149)

		cv.So(IsLegitPelicanKey(k), cv.ShouldEqual, true)
		cv.So(IsLegitPelicanKey(k2), cv.ShouldEqual, true)

		cv.So(IsLegitPelicanKey(r1), cv.ShouldEqual, false)
		cv.So(IsLegitPelicanKey(r2), cv.ShouldEqual, false)
	})
}
